# Little Lemon analysis and sales report

In [ ]:
# from mysql.connector.pooling import MySQLConnectionPool
from mysql.connector import Error

# Step 1: Define your database configurations as a Python dictionary
dbconfig = {
    "database": "little_lemon_db",
    "user": "meta_mario",
    "password": "abcd1234"
}

try:
    # Step 2: Establish a connection pool [pool_name = pool_b] with two connections
    pool_b = MySQLConnectionPool(pool_name="pool_b", pool_size=5, **dbconfig)
    print("Connection pool 'pool_b' created successfully.")

except Error as e:
    print(f"Error: {e}")

In [26]:


import time

max_retries = 3
retry_count = 0
connection3 = None
cursor3 = None

try:
    # Guest 1
    connection1 = pool_b.get_connection()
    cursor1 = connection1.cursor()
    cursor1.execute("""
        INSERT INTO Bookings (TableNo, GuestFirstName, GuestLastName, BookingSlot, EmployeeID, Status)
        VALUES (8, 'Anees', 'Java', '18:00:00', 6, 'Waiting')
    """)
    connection1.commit()

    # Guest 2
    connection2 = pool_b.get_connection()
    cursor2 = connection2.cursor()
    cursor2.execute("""
        INSERT INTO Bookings (TableNo, GuestFirstName, GuestLastName, BookingSlot, EmployeeID, Status)
        VALUES (5, 'Bald', 'Vin', '19:00:00', 6, 'Waiting')
    """)
    connection2.commit()

    # Guest 3
    connection3 = pool_b.get_connection()  # This will attempt to exceed the pool size
    cursor3 = connection3.cursor()
    cursor3.execute("""
        INSERT INTO Bookings (TableNo, GuestFirstName, GuestLastName, BookingSlot, EmployeeID, Status)
        VALUES (12, 'Jay', 'Kon', '19:30:00', 6, 'Waiting')
    """)
    connection3.commit()

except Error as e:
    print(f"Error: {e}")

finally:
    # Return the connections back to the pool
    try:
        if cursor1:
            cursor1.close()
        if connection1:
            connection1.close()

        if cursor2:
            cursor2.close()
        if connection2:
            connection2.close()

        if cursor3:
            cursor3.close()
        if connection3:
            connection3.close()  # This will raise PoolError

    except Error as e:
        print(f"Error: {e}")

In [27]:
import mysql.connector
from mysql.connector import pooling

# Set up the connection pool
pool_b = mysql.connector.pooling.MySQLConnectionPool(
    pool_name="mypool",
    pool_size=5,
    host="localhost",
    database="little_lemon_db",
    user="meta_mario",
    password="abcd1234"
)

try:
    # Task 3.1: Name and EmployeeID of the Little Lemon Manager
    connection = pool_b.get_connection()
    cursor = connection.cursor()
    cursor.execute("""
        SELECT Name, EmployeeID 
        FROM employees 
        WHERE Role = 'Manager';
    """)
    manager = cursor.fetchone()
    if manager:
        print(f"Manager: {manager[0]}, EmployeeID: {manager[1]}")
    else:
        print("No manager found.")

    # Task 3.2: Name and Role of the Employee with the Highest Salary
    cursor.execute("""
        SELECT Name, Role 
        FROM employees 
        ORDER BY Annual_Salary DESC 
        LIMIT 1;
    """)
    highest_salary_employee = cursor.fetchone()
    if highest_salary_employee:
        print(f"Highest Salary Employee: {highest_salary_employee[0]}, Role: {highest_salary_employee[1]}")
    else:
        print("No employee data found.")

    # Task 3.3: Number of Guests Booked Between 18:00 and 20:00
    cursor.execute("""
        SELECT COUNT(*) AS NumberOfGuests 
        FROM Bookings 
        WHERE BookingSlot BETWEEN '18:00:00' AND '20:00:00';
    """)
    number_of_guests = cursor.fetchone()[0]
    print(f"Number of Guests Booked Between 18:00 and 20:00: {number_of_guests}")

    # Task 3.4: Full Name and BookingID of Guests Waiting to be Seated
    cursor.execute("""
        SELECT CONCAT(GuestFirstName, ' ', GuestLastName) AS FullName, BookingID 
        FROM Bookings 
        WHERE Status = 'Waiting'
        ORDER BY BookingSlot ASC;
    """)
    waiting_guests = cursor.fetchall()
    print("Guests Waiting to be Seated:")
    for guest in waiting_guests:
        print(f"FullName: {guest[0]}, BookingID: {guest[1]}")

except mysql.connector.Error as e:
    print(f"Error: {e}")

finally:
    if cursor:
        cursor.close()
    if connection:
        connection.close()

Manager: Mario Gollini, EmployeeID: 1
Highest Salary Employee: Mario Gollini, Role: Manager
Number of Guests Booked Between 18:00 and 20:00: 24
Guests Waiting to be Seated:
FullName: Anees Java, BookingID: 18
FullName: Anees Java, BookingID: 21
FullName: Anees Java, BookingID: 24
FullName: Bald Vin, BookingID: 19
FullName: Bald Vin, BookingID: 22
FullName: Bald Vin, BookingID: 25
FullName: Jay Kon, BookingID: 20
FullName: Jay Kon, BookingID: 23
FullName: Jay Kon, BookingID: 26

In [18]:
try:
    # Guest 1
    connection1 = pool_b.get_connection()
    cursor1 = connection1.cursor()
    cursor1.execute("""
        INSERT INTO Bookings (TableNo, GuestFirstName, GuestLastName, BookingSlot, EmployeeID, Status)
        VALUES (8, 'Anees', 'Java', '18:00:00', 6, 'Waiting')
    """)
    connection1.commit()

    # Guest 2
    connection2 = pool_b.get_connection()
    cursor2 = connection2.cursor()
    cursor2.execute("""
        INSERT INTO Bookings (TableNo, GuestFirstName, GuestLastName, BookingSlot, EmployeeID, Status)
        VALUES (5, 'Bald', 'Vin', '19:00:00', 6, 'Waiting')
    """)
    connection2.commit()

    # Guest 3
    connection3 = pool_b.get_connection()  # This will attempt to exceed the pool size
    cursor3 = connection3.cursor()
    cursor3.execute("""
        INSERT INTO Bookings (TableNo, GuestFirstName, GuestLastName, BookingSlot, EmployeeID, Status)
        VALUES (12, 'Jay', 'Kon', '19:30:00', 6, 'Waiting')
    """)
    connection3.commit()

except Error as e:
    print(f"Error: {e}")

finally:
    # Return the connections back to the pool
    try:
        if cursor1:
            cursor1.close()
        if connection1:
            connection1.close()

        if cursor2:
            cursor2.close()
        if connection2:
            connection2.close()

        if cursor3:
            cursor3.close()
        if connection3:
            connection3.close()  # This will raise PoolError

    except Error as e:
        print(f"Error: {e}")

In [28]:
import mysql.connector
from mysql.connector import pooling

# Set up the connection pool
pool_b = mysql.connector.pooling.MySQLConnectionPool(
    pool_name="mypool",
    pool_size=5,
    host="localhost",
    database="little_lemon_db",
    user="meta_mario",
    password="abcd1234"
)

try:
    # Task 3.1: Name and EmployeeID of the Little Lemon Manager
    connection = pool_b.get_connection()
    cursor = connection.cursor()
    cursor.execute("""
        SELECT Name, EmployeeID 
        FROM employees 
        WHERE Role = 'Manager';
    """)
    manager = cursor.fetchone()
    if manager:
        print(f"Manager: {manager[0]}, EmployeeID: {manager[1]}")
    else:
        print("No manager found.")

    # Task 3.2: Name and Role of the Employee with the Highest Salary
    cursor.execute("""
        SELECT Name, Role 
        FROM employees 
        ORDER BY Annual_Salary DESC 
        LIMIT 1;
    """)
    highest_salary_employee = cursor.fetchone()
    if highest_salary_employee:
        print(f"Highest Salary Employee: {highest_salary_employee[0]}, Role: {highest_salary_employee[1]}")
    else:
        print("No employee data found.")

    # Task 3.3: Number of Guests Booked Between 18:00 and 20:00
    cursor.execute("""
        SELECT COUNT(*) AS NumberOfGuests 
        FROM Bookings 
        WHERE BookingSlot BETWEEN '18:00:00' AND '20:00:00';
    """)
    number_of_guests = cursor.fetchone()[0]
    print(f"Number of Guests Booked Between 18:00 and 20:00: {number_of_guests}")

    # Task 3.4: Full Name and BookingID of Guests Waiting to be Seated
    cursor.execute("""
        SELECT CONCAT(GuestFirstName, ' ', GuestLastName) AS FullName, BookingID 
        FROM Bookings 
        WHERE Status = 'Waiting'
        ORDER BY BookingSlot ASC;
    """)
    waiting_guests = cursor.fetchall()
    print("Guests Waiting to be Seated:")
    for guest in waiting_guests:
        print(f"FullName: {guest[0]}, BookingID: {guest[1]}")

except mysql.connector.Error as e:
    print(f"Error: {e}")

finally:
    if cursor:
        cursor.close()
    if connection:
        connection.close()

Manager: Mario Gollini, EmployeeID: 1
Highest Salary Employee: Mario Gollini, Role: Manager
Number of Guests Booked Between 18:00 and 20:00: 24
Guests Waiting to be Seated:
FullName: Anees Java, BookingID: 18
FullName: Anees Java, BookingID: 21
FullName: Anees Java, BookingID: 24
FullName: Bald Vin, BookingID: 19
FullName: Bald Vin, BookingID: 22
FullName: Bald Vin, BookingID: 25
FullName: Jay Kon, BookingID: 20
FullName: Jay Kon, BookingID: 23
FullName: Jay Kon, BookingID: 26

In [29]:
from mysql.connector.pooling import MySQLConnectionPool
from mysql.connector import Error

# Step 1: Define your database configurations and create a connection pool
dbconfig = {
    "database": "little_lemon_db",
    "user": "meta_mario",
    "password": "abcd1234"
}

try:
    # Create a connection pool named 'pool_b' with two connections
    pool_b = MySQLConnectionPool(pool_name="pool_b", pool_size=2, **dbconfig)
    print("Connection pool 'pool_b' created successfully.")

    # Step 2: Get a connection from the pool
    connection = pool_b.get_connection()
    cursor = connection.cursor()

    # Step 3: Create the stored procedure BasicSalesReport
    create_procedure_query = """
    CREATE PROCEDURE BasicSalesReport()
    BEGIN
        SELECT 
            SUM(BillAmount) AS Total_Sales,
            AVG(BillAmount) AS Average_Sale,
            MIN(BillAmount) AS Minimum_Bill_Paid,
            MAX(BillAmount) AS Maximum_Bill_Paid
        FROM Orders;
    END
    """
    
    # Drop the stored procedure if it already exists
    cursor.execute("DROP PROCEDURE IF EXISTS BasicSalesReport")

    # Execute the query to create the stored procedure
    cursor.execute(create_procedure_query)
    print("Stored procedure BasicSalesReport created successfully.")

    # Step 4: Call the stored procedure BasicSalesReport
    cursor.callproc('BasicSalesReport')

    # Step 5: Fetch and display the results
    for result in cursor.stored_results():
        sales_report = result.fetchall()
        print("Sales Report:")
        print(f"Total Sales: {sales_report[0][0]}")
        print(f"Average Sale: {sales_report[0][1]}")
        print(f"Minimum Bill Paid: {sales_report[0][2]}")
        print(f"Maximum Bill Paid: {sales_report[0][3]}")

except Error as e:
    print(f"Error: {e}")

finally:
    # Ensure cursor and connection are closed properly
    if cursor:
        cursor.close()
    if connection:
        connection.close()
    print("Connection closed and returned to pool.")

Connection pool 'pool_b' created successfully.
Stored procedure BasicSalesReport created successfully.
Sales Report:
Total Sales: 243
Average Sale: 48.6000
Minimum Bill Paid: 37
Maximum Bill Paid: 86
Connection closed and returned to pool.

In [23]:
from mysql.connector.pooling import MySQLConnectionPool
from mysql.connector import Error

# Step 1: Define your database configurations and create a connection pool
dbconfig = {
    "database": "little_lemon_db",
    "user": "meta_mario",
    "password": "abcd1234"
}

try:
    # Create a connection pool named 'pool_b' with two connections
    pool_b = MySQLConnectionPool(pool_name="pool_b", pool_size=2, **dbconfig)
    print("Connection pool 'pool_b' created successfully.")

    # Step 2: Get a connection from the pool
    connection = pool_b.get_connection()

    # Step 3: Create a buffered cursor
    cursor = connection.cursor(buffered=True)

    # Step 4: Combine the data from the Bookings and Employee tables,
    # Sort the retrieved records in ascending order, and display the first three guests
    query = """
    SELECT 
        BookingSlot, 
        CONCAT(Bookings.GuestFirstName, ' ', Bookings.GuestLastName) AS Guest_name,
        CONCAT(Employees.Name, ' [', Employees.Role, ']') AS Assigned_To
    FROM 
        Bookings
    LEFT JOIN 
        Employees ON Bookings.EmployeeID = Employees.EmployeeID
    ORDER BY 
        BookingSlot ASC
    LIMIT 3
    """

    cursor.execute(query)
    upcoming_bookings = cursor.fetchall()

    # Step 5: Display the information of the first three guests
    print("Next three upcoming bookings:")
    for booking in upcoming_bookings:
        print(f"[{booking[0]}] [Guest_name: {booking[1]}] [Assigned to: {booking[2]}]")

except Error as e:
    print(f"Error: {e}")

finally:
    # Step 6: Return the connection back to the pool
    if cursor:
        cursor.close()
    if connection:
        connection.close()
    print("Connection closed and returned to pool.")

Connection pool 'pool_b' created successfully.
Next three upcoming bookings:
[15:00:00] [Guest_name: Vanessa McCarthy] [Assigned to: Giorgos Dioudis [Head Chef]]
[17:30:00] [Guest_name: Marcos Romero] [Assigned to: Fatma Kaya [Assistant Chef]]
[18:00:00] [Guest_name: Anees Java] [Assigned to: John Millar [Receptionist]]
Connection closed and returned to pool.